### PR TITLE
Fix nodenext module support from TypeScript 4.7

### PR DESCRIPTION
**Pull request by wight554**
* as per https://github.com/microsoft/TypeScript/issues/48235#issuecomment-1067363731
* follow-up https://github.com/preactjs/preact/pull/3513

### CODE REVIEW

**Comment by wight554** [comment]
Can be shimmed by:
```
declare module 'htm/preact' {
  export * from 'node_modules/htm/preact/index.js';
}
```
But it would be better to fix it properly

**Comment by wight554** [comment]
cc @developit

**Review by developit — APPROVED** [review]
Looks correct to me!

**Comment by developit** [comment]
Thanks @wight554 - published as [3.1.1](https://github.com/developit/htm/releases/tag/3.1.1).

**Pull request merged**
